### ISSUE TITLE
Debian 10 Buster compatibility

### ISSUE THREAD

**Issue by apiening** [mrlesmithjr/ansible-shorewall#15]
Debian 10 alias Buster comes with shorewall 5.2 (version 5.2.3.2 at the time of writing on my system).
Shorewall check complains with the following message: `ERROR: Unknown Action (Drop) in DROP_DEFAULT setting /usr/share/shorewall/actions.std (EOF)`
The message is a little bit misleading, since the definition of `DROP_DEFAULT` is set in `/etc/shorewall/shorewall.conf`.

When I replace the following section unter `DEFAULT ACTIONS/MACROS`
```
ACCEPT_DEFAULT=none
DROP_DEFAULT=Drop
NFQUEUE_DEFAULT=none
QUEUE_DEFAULT=none
REJECT_DEFAULT=Reject
```
with this one
```
ACCEPT_DEFAULT="none"
BLACKLIST_DEFAULT="dropBcasts,dropNotSyn,dropInvalid"
DROP_DEFAULT="Broadcast(DROP),Multicast(DROP)"
NFQUEUE_DEFAULT="none"
QUEUE_DEFAULT="none"
REJECT_DEFAULT="Broadcast(DROP),Multicast(DROP)"
```
`shorewall check` does not complain anymore.

Would it be possible to add an alternative template file for `shorewall.conf` for Debian Buster with these settings?
Another option would be to configure these options via variables.

**Comment by apiening** [comment]
I took a closer look and found a workaround or temporary solution that I would like to share.
In my ansible playbook I've set `shorewall_version: 5buster` and then I created a copy of `shorewallv5.conf.j2` and placed it in `templates/etc/shorewall/shorewallv5buster.conf.j2`.
I then replaced the lines in the section `DEFAULT ACTIONS/MACROS` like shown above.
Because of the `shorewall_version` setting my modified template file gets picked up and the playbook applies without issues.

**Comment by mrlesmithjr** [comment]
@apiening Thanks for reporting this. I'll do some testing here soon and include Debian Buster and also need to test with Ubuntu Dingo.

**Comment by mrlesmithjr** [comment]
@apiening The latest changes in master should now address your issue that you experienced.

**Comment by Nowi5** [comment]
I just updated Debian from 9 to 10 and have the same issue. Even reinstall of Debian didn't solved that.

**Comment by mrlesmithjr** [comment]
@Nowi5 Thanks for reporting back. I've reopened the issue and will look into this as time permits.

**Comment by apiening** [comment]
@Nowi5 I'm also on Debian 10 but the initial issue that `shorewall` was not starting with the generated config was solved by the update from @mrlesmithjr in late july. At least it is working for me since then.

However, I do get a few warnings from `shorewall check`:
```
   WARNING: The CHAIN_SCRIPTS configuration option is no longer supported /etc/shorewall/shorewall.conf (line 149)
   WARNING: The INLINE_MATCHES configuration option is no longer supported /etc/shorewall/shorewall.conf (line 185)
   WARNING: The LOAD_HELPERS_ONLY configuration option is no longer supported /etc/shorewall/shorewall.conf (line 193)
   WARNING: The MAPOLDACTIONS configuration option is no longer supported /etc/shorewall/shorewall.conf (line 201)
   WARNING: The MODULE_SUFFIX configuration option is no longer supported /etc/shorewall/shorewall.conf (line 207)
```

So it looks like the generated `shorewall.conf` is not a clean one based on the most current example provided by shorewall.

Other than that, shorewall is working and behaving correctly for me as fas as I can tell.
Can you please post the relevant output of `shorewall check` or add more details about your issue or the errors you get?

**Comment by apiening** [comment]
@Nowi5 are you still experiencing this issue?
I just applied the role to a Debian 10 host without issues.

Please provide additional information on the error you have.
In case you have found a solution for your issue please let us know.

Otherwise I would close this issue.

**Comment by apiening** [comment]
This issue was reported by me quite a while ago, then it was fixed and closed.
It was reopened based on an issue reported by @Nowi5, but no additional feedback has been provided since then.
Closing this issue.

**Comment by drebs** [comment]
FTR: I experienced the same issue after upgrading a system from Debian 9 to 10, and then to 11.

The problem was solved by replacing the old `/etc/shorewall/shorewall.conf` by the `.dpkg-dist` version, and then running Puppet once again.

**Comment by apiening** [comment]
Running Puppet again?

**Comment by drebs** [comment]
Oops, sorry, my bad. Nevermind my last comment!
